file_name: /scratch1/brizk/ADNI_SCREENING_DATA/cnn_results/model/1007_pooling_age
data:
  data_type: t1_linear
  dir_to_scans: /scratch1/brizk/ADNI_SCREENING_DATA/processed/subjects
  dir_to_tsv: /scratch1/brizk/ADNI_SCREENING_DATA/splits
  batch_size: 4
  val_batch_size: 2
  workers: 1
  percentage_usage: 1.0
exp_name: 1007_pooling_age
visdom:
  port: 
  server: 
model:
  arch: ours
  input_channel: 1
  nhid: 512
  feature_dim: 1024
  n_label: 3
  expansion: 8
  num_blocks: 0
  type_name: conv3x3x3
  norm_type: Instance
adv_model:
  nhid: 36
  out_dim: 12
mmse_model:
  nhid: 64
training_parameters:
  use_age: False
  pretrain:  #dir to saved model here
  max_iter: 16000
  start_epoch: 0
  epochs: 200
  print_freq: 10
  max_grad_l2_norm:
  report_interval: 100
  snapshot_interval: 1000

optimizer:
  method: SGD
  par:
    lr: 0.01
    weight_decay: 0.000

