file_name: !ENV /scratch1/${USER}/alz/ALL_ADNI_MRI_T1/cnn_results/model/exp_batch_16_lr_0.01_weight_decay_0.000
data:
  data_type: t1_volume
  dir_to_scans: !ENV  /scratch1/${USER}/alz/ALL_ADNI_MRI_T1/ADNI_CAPS/subjects
  dir_to_tsv: !ENV /scratch1/${USER}/alz/ALL_ADNI_MRI_T1/ADNI_SPLITS
  batch_size: 16
  val_batch_size: 2
  workers: 4
  percentage_usage: 1.0
exp_name: exp_batch_16_lr_0.01_weight_decay_0.000

visdom:
  port: 
  server:
model:
  arch: ours
  input_channel: 1
  nhid: 512
  feature_dim: 1024
  n_label: 3
  expansion: 8
  num_blocks: 0
  type_name: conv3x3x3
  norm_type: Instance
adv_model:
  nhid: 36
  out_dim: 12
mmse_model:
  nhid: 64
training_parameters:
  use_age: False
  pretrain: !ENV /scratch1/${USER}/alz/ALL_ADNI_MRI_T1/cnn_results/model/exp_batch_16_lr_0.01_weight_decay_0.000
  max_iter: 16000
  start_epoch: 0
  epochs: 200
  print_freq: 10
  max_grad_l2_norm:
  report_interval: 100
  snapshot_interval: 1000

optimizer:
  method: SGD
  par:
    lr: 0.01
    weight_decay: 0.000

